fix(web): Disable triggering fiat permission sync when creating application
mercari/front50 pull request #1
Opened 2020-12-02 09:49 UTC by dragon3

## WHAT

This pull request disables triggering fiat permission sync when creating application.

## WHY

As described in https://github.com/spinnaker/front50/pull/995 , we have some issues around fiat permission sync.
As a workaround, we'd like to disable the fiat permission sync, only all roles sync when creating application because it's very expensive when there are many roles.

2020-12-08 03:58 UTC, KeisukeYamashita approved these changes
LGTM 👍

2020-12-08 04:24 UTC, KeisukeYamashita requested changes
Just block this merge.

2020-12-08 04:25 UTC, KeisukeYamashita requested changes
Just for blocking this merge.

2020-12-08 05:21 UTC, KeisukeYamashita approved these changes
Thank you! As far as I know, it should be okay 🚀

2020-12-09 01:11 UTC, merged

2020-12-09 01:13 UTC, dragon3 commented
Thank you for the review!  Merged 💪

2020-12-09 01:15 UTC, dragon3 commented
Added tag `release-1.23.3-mercari.2` for this change.
https://github.com/mercari/front50/releases/tag/release-1.23.3-mercari.2