fix(web): Disable triggering fiat permission sync when creating application (1.20.x)
mercari/front50 pull request #2
Opened 2020-12-03 02:16 UTC by dragon3

## WHAT

This pull request disables triggering fiat permission sync when creating application.
This is for Spinnaker version `1.20.x`.

## WHY

As described in https://github.com/spinnaker/front50/pull/995 , we have some issues around fiat permission sync.
As a workaround, we'd like to disable the fiat permission sync, only all roles sync when creating application because it's very expensive when there are many roles.

## REF

- https://github.com/mercari/front50/pull/1

2020-12-08 03:59 UTC, KeisukeYamashita approved these changes
LGTM, thank you.

2020-12-08 04:25 UTC, KeisukeYamashita requested changes
Just for blocking this merge.

2020-12-08 05:22 UTC, KeisukeYamashita approved these changes
Thank you! As far as I know, it should be okay 🚀

2020-12-09 01:14 UTC, dragon3 commented
Thank you for reviewing! I'm going to merge it 💪

2020-12-09 01:15 UTC, merged

2020-12-09 01:17 UTC, dragon3 commented
Added tag `release-1.20.8-mercari.2` for this change:
https://github.com/mercari/front50/releases/tag/release-1.20.8-mercari.2